Feat/#52 qna 기능 구현
smRt-Egg/BE-05-smRt-store pull request #104
Opened 2024-01-01 07:55 UTC by voidmelody

### 상품에 대한 문의 / 답변 기능

* 문의 생성 (createQuestion)
* 유저가 생성한 문의 리스트 가져오기 (findByUserId)
* 문의 수정 (updateQuestion)
* 문의 삭제 (deleteQuestion)
* 특정 상품에 대한 문의 리스트 조회 (findByProductId)
* 특정 문의에 대한 답변 생성 (addAnswer)
* 특정 문의에 대한 답변 리스트 조회 (getAnswersByQuestionId)

2024-01-02 00:35 UTC, suzzingv requested changes

2024-01-02 00:35 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +
리뷰에 대한 답변 수정 기능은 없는 건가용?

2024-01-02 00:35 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/qna/infrastructure/ProductQuestionRepositoryImpl.java
> +public class ProductQuestionRepositoryImpl implements ProductQuestionRepositoryCustom {
jpa 함수를 쓰지 않고 query dsl을 쓰신 이유가 궁금합니다!!

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductAnswer.java
> +    private ProductQuestion productQuestion;
여러개의 질문에 대해서 하나의 답변을 달 수 있다는 것일까요?
상품 문의사항의 경우 대부분 1:1로 작성한것 같았는데 N:1 연관관계를 설정한 이유가 궁금합니다 !

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductAnswer.java
> +    }
생성자 지정도 하고 setter도 활용하는 이유가 있을까요?

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductQuestion.java
> +    }
개인적인 의견입니다!
양방향 연관관계를 설정할때 연관관계의 부모가 되는 엔티티에서 연관관계 매핑을 설정하는 거보다 자녀가 생성될 때 생성자에서 편입되는 방식을 선호하는데, 이유는 생성과정에서 연관관계 매핑까지 마무리 할 수 있다는 장점에서 위와 같은 방식을 사용합니다.

객체 생성 이후 연관관계를 따로 지정하도록 작성한 이유가 있을까요?

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductQuestion.java
> +    private Long productId;
User와 Product에 대해서 연관관계 설정을 안하고 일부러 Id로 받는 이유가 있을까요?

2024-01-02 00:59 UTC, tidavid1 commented on src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
LGTM 👍🏻

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +        questionRepository.save(productQuestion);
```suggestion
        ProductQuestion productQuestion = questionRepository.save(ProductQuestion.builder()
                .userId(request.getUserId())
                .productId(request.getProductId())
                .content(request.getContent())
                .build());
```

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +    }
하나로 합쳐서 사용하는 것은 어떨까요?

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/DeleteQuestionResponse.java
> +}
단일 인자에 대해서 DTO로 감싸는 이유가 궁금해요!

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +        checkUserExist(userId);
꼭 유저로 로그인을 해야 상품 QnA를 조회할 수 있을까요?

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/presentation/controller/ProductQnAController.java
API <-> Controller DTO 와 Controller <-> Service DTO를 분리해서 사용하지 않은 이유가 궁금하네요!

2024-01-02 00:59 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/qna/presentation/controller/ProductQnAController.java
Role 별 접근 권한을 주석으로 남겨주면 좋을 것 같습니다 👍🏻

2024-01-03 13:46 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +
만들겠습니다. 감사합니다 ^^

2024-01-03 14:53 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/infrastructure/ProductQuestionRepositoryImpl.java
> +public class ProductQuestionRepositoryImpl implements ProductQuestionRepositoryCustom {
dto를 처음부터 가져오기 위해서 사용했습니다.
JPA에서 이를 처리하려면 @Query와 함께 DTO의 패키지 구조를 명시해줘야해서 불편함을 느꼈습니다.

2024-01-03 14:55 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductAnswer.java
> +    private ProductQuestion productQuestion;
하나의 질문에 대해 여러 답변을 달 수 있다 식으로 해석했습니다.
예를 들면
Q. 해당 상품 언제 재고 들어오나요?
A1. 이번 주 수요일에 들어올 예정입니다. 재고가 들어오면 추가적으로 답변드리겠습니다.
A2. 오늘 재고가 들어왔습니다. 감사합니다.
이런 식의 상황을 가정했습니다.

2024-01-03 14:57 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductAnswer.java
> +    }
setter을 허용한 이유는, productQuestion 엔티티의 addProductAnswer() 함수에서 연관관계 함수에 필요해 허용했습니다.

2024-01-03 15:01 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductQuestion.java
> +    private Long productId;
연관관계 설정의 필요성을 느끼는 이유 중 하나가 해당 객체에 접근해 객체의 데이터에 접근할 경우가 많을 때라고 생각합니다.
현재 기능상 User와 Product 객체의 데이터에 접근(get)하는 경우의 필요성이 별로 없었습니다.
User와 Product의 테이블에 해당 객체가 존재하는지 유무 정도로만 판별하는데 사용했기에 연관관계 매핑보다는 id로만 해도 충분하다 판단했습니다.

2024-01-03 15:02 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +        questionRepository.save(productQuestion);
이건 취향 차이인 것 같네요.

2024-01-03 15:04 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +    }
path 변수나 request 인자로 userId가 오지 않는 경우(예를 들어 delete 함수의 경우 userId가 아닌 questionId만 넘어옴)
checkUserValid 함수는 호출할 이유가 없기에, 따로 구분했습니다.

2024-01-03 15:04 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/DeleteQuestionResponse.java
> +}
단순하게 id만 반환해도 되지만, 통일성을 살리기 위해서 ResponseDto로 한번 감쌌습니다.

2024-01-03 15:28 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
> +        checkUserExist(userId);
음.. 그러네요.
로그인을 꼭 해야 할 필요성은 없어보이네요.
이건 수정하겠습니다.

2024-01-04 04:45 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductQuestion.java
> +    }
말씀하신 것처럼 해당 부분은 제가 이해가 조금 부족했습니다.
생성 주기를 고려해서 자식 생성자 쪽에서 하는 걸로 수정완료했습니다. 감사합니다.

2024-01-04 05:21 UTC, suzzingv approved these changes

2024-01-07 10:48 UTC, merged