Feat/#87 coupon product
smRt-Egg/BE-05-smRt-store pull request #106
Opened 2024-01-01 13:53 UTC by YongNyeo

이전에 confilct가 나서  #59 와 #81  pr와 중복된 부분이 많습니다

#87  번을 이어서 커밋 예정입니다.

2024-01-02 00:40 UTC, suzzingv approved these changes

2024-01-02 01:14 UTC, tidavid1 approved these changes

2024-01-02 11:47 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/Calculator.java
> + */
????????

2024-01-03 10:24 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/ProductCouponResponse.java
> +    private List<UserCouponResponse>issuableCoupons;
오잉 띄어쓰기 안해도 컴파일 오류가 안나나요?🤔

2024-01-03 11:26 UTC, happyjamy reviewed
수정 사항 반영해 주세요~

2024-01-03 11:26 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +        List<Coupon> discountCoupons = new ArrayList<>();
이름을 `applicableCoupons` 이런식으로 적용 가능한 쿠폰 이라는 걸 살리면 어때요

2024-01-03 11:26 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +        }
함수 따로 뺄 것 같아요

2024-01-03 11:26 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +        Calculator calculator = new Calculator();
상태를 가지고 있지 않으면 굳이 계속 생성할 이유가 있나요

2024-01-03 11:26 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    private void validPercentValue(BenefitUnitType benefitUnitType, Long value) {
왜 valid 죠...

2024-01-03 11:26 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +        if (couponType == CouponType.DELIVERY) {
자주 사용하면 함수로 빼고, 아니면 적어도 enum에 equals() 사용해주세요

2024-01-03 11:27 UTC, happyjamy requested changes
수정 사항 반영해 주세요!

2024-01-03 12:21 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +                .collect(Collectors.toList());
반환할 리스트를 stream으로 map하거나 변경할 요지가 있다면 Colletors.toList()가 적절하다 보지만, 변경이 불가하게 하거나 이후 변경이 불필요하다면 toList()를 고려해보죵.

2024-01-03 12:26 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    @PrimaryKeyJoinColumn(name = "coupon_quantity_id")
특별하게 @PrimaryKeyJoinColumn을 사용한 이유가 있을까요?
@JoinColumn으로 pk를 해줘도 되지 않을까 생각했어요

2024-01-03 12:29 UTC, voidmelody approved these changes

2024-01-03 13:11 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/ProductCouponResponse.java
> +    private List<UserCouponResponse>issuableCoupons;
주석 말씀하시는거면 안나더라구요 😄

2024-01-03 13:16 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponQuantity.java
> +
아 요것도 락 구현해서 사용합니다!
대신 쿠폰 수량 update 메서드 사용을 AdminCouponService에서 사용할 예정입니다

2024-01-03 13:34 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +                .collect(Collectors.toList());
2개를 반대로 헷갈렸어요 수정하겠습니당!!

2024-01-03 13:36 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +        List<Coupon> discountCoupons = new ArrayList<>();
좋은 아이디어입니다

2024-01-03 14:03 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +        Calculator calculator = new Calculator();
우선순위큐 여러개가 있습니다

2024-01-03 14:08 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +        if (couponType == CouponType.DELIVERY) {
네 그런데 저는 enum은 ==로 비교하는게 컴파일 타임에 잡을수 있어서 항상 사용해왔는데
equals를 사용해야하는 이유가 있을까요?!

2024-01-03 14:20 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    @PrimaryKeyJoinColumn(name = "coupon_quantity_id")
@JoinColumn과 @Id 를 이용하는 방법과 @PrimaryKeyJoinColumn  두가지를 봤는데,
전자는 어떠한(manyToX.. 등) 관계여도 적용가능하다 후자는 일대일 매핑에서만 사용한다고 하는데
제 경우에 한눈에 보기에 편하지 않을까 해서 사용해보았습니다.
사실 팀 컨벤션에 맞춰가야할 부분이라고 생각합니다 😅

2024-01-03 14:26 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/ProductCouponResponse.java
> +    private List<UserCouponResponse>issuableCoupons;
에러 안나긴 하는데 포맷팅 (한칸 띄기) 하는게 좋을 것 같아요!

2024-01-03 14:27 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +        Calculator calculator = new Calculator();
알고king

2024-01-03 14:45 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +        if (couponType == CouponType.DELIVERY) {
equals 내부적으로 == 을 사용해서 큰 차이는 없지만,
표준적으로 equals() 를 사용해서 일관성 측면에서 말한거에요!

https://johnmarc.tistory.com/152

읽어보면 도움 될 글

2024-01-03 14:47 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +        if (couponType == CouponType.DELIVERY) {
항상 감사합니다

2024-01-03 14:50 UTC, happyjamy approved these changes

2024-01-03 14:52 UTC, merged