Feat/#136 user shipping address 수정 정보 조회, 수정, 삭제
smRt-Egg/BE-05-smRt-store pull request #137
Opened 2024-01-05 05:06 UTC by suzzingv

# 배송지 수정 시 기존 정보 불러오는 기능
- 기본 배송지의 경우 기본 배송지 여부 수정 불가 -> 클라이언트에서 처리

# 배송지 수정 기능
- 수정하려는 배송지가 기본 배송지가 아닌데 기본 배송지로 설정하고 싶은 경우, 기존의 기본 배송지를 해제해야 한다.
- 기본 배송지는 기본 배송지 여부를 선택할 수 없다.(클라이언트에서 기본 배송지일 경우 기본 배송지 선택 체크란을 주지 않음 -> 변경의 여지 없음)

# 배송지 삭제 기능
- 기본 배송지는 삭제하지 못한다.

2024-01-05 11:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
> +        }
자바 stream을 사용하지 않고 for문을 사용한 이유가 있을까요?

2024-01-06 16:25 UTC, YongNyeo approved these changes

2024-01-06 20:04 UTC, happyjamy requested changes
바꿔주세요~

2024-01-06 20:04 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
>          checkShippingAddressesSize(shippingAddresses);
Entity 안에 안있고 왜 서비스에 있나요용오옹

2024-01-06 20:04 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
> +            if ((address.getPhoneNum2() == null && shippingAddress.getPhoneNum2() == null)
이거 주석 좀 달아주세요

2024-01-06 20:04 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
> +        }
```suggestion
shippingAddresses.removeIf(address -> address.getId().equals(shippingId));

```

2024-01-07 06:04 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
>          checkShippingAddressesSize(shippingAddresses);
예외를 던져야 하는데 예외 처리는 서비스에서 하는 것이 적절하다고 생각해서 서비스로 뺐습니다! 엔티티에서 예외처리를 하는 것에 대한 주환 님의 생각이 궁금합니다!

2024-01-07 07:06 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
>          checkShippingAddressesSize(shippingAddresses);
Entity 내부에서도 예외를 던지는게 이상하다고 생각하지 않아용!
shipping address 라는 도메인과 직접적인 필드의 검증이기때문에 도메인 내부에 있는게 맞는것 같아요~

2024-01-07 07:13 UTC, tidavid1 approved these changes

2024-01-07 11:33 UTC, happyjamy approved these changes

2024-01-07 13:57 UTC, merged