Feat/#134 product controller 목록조회, 생성 기능 구현
smRt-Egg/BE-05-smRt-store pull request #141
Opened 2024-01-05 12:44 UTC by tidavid1

- [ ] Product Detail 호출 구현
  - #134 
  - coupon과 point service가 필요해 develop에 병합되는 대로 진행하도록 하겠습니다.
- [x] Product 목록 조회 구현
  - close #135 
- [x] Product 생성 구현
  - close #140 
- [x] Product 할인 설정
  - close #147

2024-01-06 17:10 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +    @Secured("ROLE_ADMIN")
pr 컨트롤러에서는 처음보는거같은데 간단한 설명 부탁드립니다! 
뭔가 admin에서 공통적으로 써야할 것 같아서요!

2024-01-06 17:10 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAPIRequest.java
> +    private String thumbnailUrl;
String으로 쓰실거면 NotBlank 써야할 것 같아요! 
혹시 URL 형식으로 들어가서 null이 맞나용..?

2024-01-06 17:10 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAPIRequest.java
> +    }
return을 catch문 안에 넣는게 좋지 않을까용

2024-01-06 19:52 UTC, happyjamy requested changes
요청 사항 반영해줗세요!

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductThumbnailResponse.java
> +    private Float discountRatio;
`Double` 안쓰고 `Float` 쓴 이유는?

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +    public ResponseEntity<ProductAPIResponse> createProduct(
`ResponseEntity` 로 감싸는걸로 통일하나용!!!

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +            request.getDiscountRatio().equals(0F) ? productService.disableProductDiscount(productId)
매직넘버 따로 빼주세요! 근데 이건 뭔가요...

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +
요고 `style` 로 고치는게 어떨까용 ㅎㅎ

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAPIRequest.java
> +    private String thumbnailUrl;
@NotNull 로 null 검사하고, @URL 은 empty 한 값에 대한 검사도 해줍니다!
String 은 객체라 null 들어갈 수 있어요.

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAPIRequest.java
> +        } catch (MalformedURLException ignore) {
왜 ignore 하는지 주석으로 써주세요!

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAPIRequest.java
> +    }
22

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/ProductDiscountRatioAPIRequest.java
> +    Float discountRatio;
여기도 Double 아닌 이유!

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/ProductDiscountRatioAPIRequest.java
> +    @Min(value = 0, message = "할인률은 0 이상이어야 합니다.")
요론건 비즈니스 로직에서 하는게 좋을 것 같기두?
도메인에서 update 할때는 무조건 넣어주세요!

2024-01-06 19:52 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductAPIResponse.java
> +        return new ProductAPIResponse(
이정도면 빌더해야하는거 아닌지...

2024-01-07 04:42 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +    @Secured("ROLE_ADMIN")
저번에 이야기했던 메서드별 권한 설정 관련된 어노테이션입니다! `@Secured("ROLE_ADMIN")` 을 사용하면 Admin 권한이 없는 유저는 403이 발생해요!

2024-01-07 04:54 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductThumbnailResponse.java
> +    private Float discountRatio;
0~100 사이의 값이 들어갈 것이라서 굳이 8bit 연산인 Double을 써야할까? 생각했습니다

2024-01-07 04:54 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +    public ResponseEntity<ProductAPIResponse> createProduct(
다른 컨트롤러 코드가 ResponseEntity를 사용해서 동일하게 작성해봤습니다! 다른 커스텀 Response가 있을까요?

2024-01-07 04:55 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +            request.getDiscountRatio().equals(0F) ? productService.disableProductDiscount(productId)
할인을 0으로 선언하면 할인 설정을 해제한다는 옵션입니다 :D

2024-01-07 07:09 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/ProductDiscountRatioAPIRequest.java
> +    Float discountRatio;
위와 동일합니다 :D

2024-01-07 07:11 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/ProductDiscountRatioAPIRequest.java
> +    @Min(value = 0, message = "할인률은 0 이상이어야 합니다.")
비즈니스 로직 상에서도 필터링을 해서 괜찮을 것같습니다 :D

2024-01-07 07:21 UTC, suzzingv approved these changes

2024-01-07 08:33 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductThumbnailResponse.java
> +    private Float discountRatio;
근데 그렇게 따지면 할인률이 `23.5%` 이렇게 나오진 않을텐데 `integer` 써도 되는거 아닌가요?!

2024-01-07 13:21 UTC, YongNyeo approved these changes

2024-01-07 13:53 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
> +    public ResponseEntity<ProductAPIResponse> createProduct(
아뇽!! 보통 ProductAPIResponse 만 적어도 스프링이 알아서 body 에 넣어주는데 굳이 명시한 이유가 궁금해서요!
명시하는 것도 좋은 것 같습니다!

2024-01-07 13:58 UTC, happyjamy approved these changes

2024-01-07 14:05 UTC, merged