Feat/#167 admin coupon service
smRt-Egg/BE-05-smRt-store pull request #168
Opened 2024-01-08 06:34 UTC by YongNyeo

Admin Service에서

쿠폰 생성, 조회
쿠폰 수량 변경
상품에 대한 쿠폰 적용,취소
사용자에 대한 쿠폰 적용(CouponPublicationType 의 Allocate 방식) , 취소

쿠폰 유/무효화 (@scheduled사용)
- @Scheduled를 이용해 자정마다 유효기간이 지난 쿠폰은 무효화 작업을 진행
- 다른 기술을 사용하기에 시간,기술적 여유가 없어 최소한의 기능 구현 목적으로 @scheduled 사용

2024-01-08 08:50 UTC, happyjamy approved these changes
LGTM👍

2024-01-08 09:15 UTC, tidavid1 requested changes
리뷰 확인해주세여!

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/SmRtStoreApplication.java
> +@EnableScheduling
스캐줄링을 배치로 구현하기로 한 것같은데 아닌가요...?

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
> +        }
`.ifPresent()`를 사용하면 if문 안쓰고도 예외 호출이 가능할 것 같아요!

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
> +        }
위에랑 동일한 의견입니다!

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
> +    }
무효, 유효화에 대한 리턴값은 없는것일까요?

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
> +    @Scheduled(cron = "0 0 0 * * *") // 매일 자정 00:00에 실행
배치 스크립트 활용해서 처리하기로 한 것같은데 스케쥴링으로 처리한 이유가 따로 있을까요? 🍡

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
> +    }
제거랑 회수에 대한 리턴값도 고민해봐야 할 듯 합니다

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
> +    }
`AdminCouponService`와 중첩되는 로직으로 보여지는데 하나에서 관리하는 것은 어떨까요?

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +            return 0L;
매직넘버 처리하면 좋을 것 같습니다  :D

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +        Long discountPrice = couponValue.getBenefitValue() * price / 100;
이부분도 메서드 따로 작성해서 활용하는게 어떤 로직인지 명확하게 볼 수 있을것같아요!

2024-01-08 09:15 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustomImpl.java
> +        em.clear();
왜 EntityManager가 필요했는지 궁금합니다! 설명 코멘트로 달아주세요!! 📟

2024-01-08 09:26 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/SmRtStoreApplication.java
> +@EnableScheduling
회의때 뭐로 하기로 결정은 안했고 
멘토님이 스크립트로 하면 어려울거다라고 하셔서 
pr설명에 적었다시피 스케줄링으로 구현했습니다!
스크립트 구현 얼마나 걸릴지 감이 안와서 하더라도 최후에 구현할 예정입니당

2024-01-08 09:27 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
> +    }
예... 
업데이트 처럼 리턴값이 없다고 생각하고 구현했습니다!

2024-01-08 09:33 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +        Long discountPrice = couponValue.getBenefitValue() * price / 100;
매직넘버 말씀하시는걸까용?

2024-01-08 09:37 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustomImpl.java
> +        em.clear();
해당 메서드는 영속성 컨텍스트에는 변경사항없이 
쿼리를 통해 DB에 반영이 되기 때문에
같은 영속성 컨텍스트(@Transactional)안에서 다시 불러오면 바뀐 DB 내용을 불러오지 못해서
따라서 수동으로 (entity manager를 선언,주입 후) flush(), clear()를 해서 한번 비워줘야 
영속성컨텍스트에 바뀐 DB값을 불러올 수 있습니다.
물론 여기서는 update 이후에 영속성컨텍스트에서 값을 안쓰기 때문에 상관없지만
관례적으로 많이 쓴다고해서 사용했습니당

2024-01-08 10:10 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/SmRtStoreApplication.java
> +@EnableScheduling
Point는 배치로 구현한다고 해서 한번 확인해보면 좋을 것 같네요 👀

2024-01-08 10:11 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
> +    }
업데이트는 업데이트된 결과값을 반환해주면 좋지 않을까요??

2024-01-08 10:11 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +        Long discountPrice = couponValue.getBenefitValue() * price / 100;
`Long discountPrice = calculateDiscountValue(price)` 이런 방식이요!

2024-01-09 02:04 UTC, tidavid1 approved these changes
LGTM! 👍🏻

2024-01-10 19:16 UTC, voidmelody approved these changes

2024-01-10 19:17 UTC, voidmelody commented
전반적으로 잘 작성하셨습니다..^^.. 
로직 부분이 매우 까다로워 보이는데 화이팅입니다.!

2024-01-11 14:26 UTC, merged