Refact/#166 user refactoring
smRt-Egg/BE-05-smRt-store pull request #176
Opened 2024-01-08 13:13 UTC by suzzingv

# Repository
- findById 소프트 삭제 적용 위한 쿼리 어노테이션 추가

# Service
- update 시 수정된 값만 받도록 수정
-> 엔티티 안에서 유효성 검사
-> boolean wrapper 클래스로 바꾸면서 다른 도메인에서 user boolean 필드 쓴 경우 함수 이름이 is -> get으로 변경 (머지 시 충돌)
- user, shipping service 나눠서 facade 패턴 적용
- 엔티티에서 해야할 작업을 엔티티 안으로 이동
- 재구매 필드, 함수 삭제
-> order 도메인과 협의 후 다르게 처리해야할 것 같아 삭제

2024-01-08 13:36 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    INAPPROPRIATE_ADDRESS_2_DEPTH_LENGTH(BAD_REQUEST, "상세 주소의 길이는 1~30자여야 합니다."),
inappropriate라는 표현이 마음에 들지 않는데 단어 추천 부탁드립니당

2024-01-08 13:36 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/application/ShippingAddressService.java
> +    public static final int MAXIMUM_SHIPPING_SIZE = 15;
user entity 안에서 쓰는 값인데 엔티티 안에서 선언하는 게 어색하다고 생각해서 여기다 선언하고 썼는데 의견 부탁드립니당

2024-01-08 13:36 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/UpdateUserRequest.java
> +    @Email
수정할 필드만 넘기도록 하려면 수정하지 않는 필드에는 null이 들어가야 하므로, update dto의 null 체크는 하지 않는 게 맞다고 생각해 null 검사를 다 지웠습니다. 제가 제대로 이해하고 적용한 것이 맞는지 궁금합니다!

2024-01-08 23:57 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    INAPPROPRIATE_ADDRESS_2_DEPTH_LENGTH(BAD_REQUEST, "상세 주소의 길이는 1~30자여야 합니다."),
INVALID?

2024-01-09 00:29 UTC, tidavid1 requested changes

2024-01-09 00:29 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/ShippingAddressService.java
> +    public static final int MAXIMUM_SHIPPING_SIZE = 15;
도메인이 서비스를 역참조하는 형태보다 유저 도메인 내부에서 선언하는게 더 맞는거 같습니다.
도메인 엔티티 내부에 private static 으로 선언해도 될것같아요

2024-01-09 00:29 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserFacadeImpl.java
서비스에 대한 Facade는 presentation에 위치하면 좋을 것 같다는 생각입니다! 다른 도메인에서는 여러 레포지토리를 하나의 파사드로 묶은 경우에 대한 파사드를 application 레이어에 두고 있어요! 통일하면 좋을 것 같습니다

2024-01-09 00:29 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
> +    }
전화번호와 같이 동일한 Pattern을 사용하는 경우에 대해서는 private static 선언으로 Pattern을 저장하고 이를 활용하는 방식은 어떨까요?

2024-01-09 00:29 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
> +        if (address1Depth.isEmpty() || recipient.length() > 30) {
```suggestion
        if (address2Depth.isEmpty() || recipient.length() > 30) {
```

2024-01-09 00:29 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
>      }
String 인풋이 " "공백값이 들어온 경우에 대한 검증도 필요할 것 같아요

2024-01-09 00:29 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
> +    }
패턴 객체가 호출시마다 생성되는 형태보다 private static 으로 관리하는 것이 더 좋아보이는데 의견이 궁금해요!

2024-01-09 03:04 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    INAPPROPRIATE_ADDRESS_2_DEPTH_LENGTH(BAD_REQUEST, "상세 주소의 길이는 1~30자여야 합니다."),
오 좋은 것 같아요 감사합니당ㅇ

2024-01-09 03:14 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
> +        if (address1Depth.isEmpty() || recipient.length() > 30) {
와 감사합니다!

2024-01-09 03:17 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
>      }
네이버 쇼핑 폼에서는 아예 공백값을 입력할 수가 없도록 커서가 뒤로 가지 않던데 이런 경우에도 검증이 필요한지 의견이 궁금합니당 저도 고민을 했던 부분이었습니다!

2024-01-09 08:36 UTC, tidavid1 approved these changes

2024-01-09 16:32 UTC, merged