Feat/#192 user identify verification
smRt-Egg/BE-05-smRt-store pull request #194
Opened 2024-01-10 19:15 UTC by suzzingv

## 🚀 개발 사항
# Service
- email로 랜덤 코드 보내는 기능 구현
- 입력한 코드가 전송한 코드와 같은지 확인하는 기능 구현

# Gradle Dependency
- redis gradle 추가
- redis testcontainer 생성 위한 gradle 추가

# core/config
- test에서는 testcontainer, main에서는 local에서 redis container 띄우도록 redisConfig 분리

### 이슈 번호
close

## 특이 사항 🫶

2024-01-11 02:17 UTC, tidavid1 requested changes
test/resources/application.yml 생성대신 main/resources/application.yml 에 profile 분기 방식을 선택한 것 같은데 이유가 있을까요?
추가적으로 테스트에서 redis 활용이 필요할때 `@Testcontainers` 선언으로 자동 생성이 가능한 것으로 알고있는데 따로 test용 config을 작성해주신 이유도 궁금해요!

2024-01-11 02:17 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    VERIFICATION_CODE_ERROR(UNAUTHORIZED, "인증 코드가 올바르지 않습니다."),
 Prefix로 `EMAIL_` 붙여주면 좋을거같아요

2024-01-11 02:17 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
> +@Transactional
외부 서비스를 전송하는 경우에 대해서 `@Transactional`작성한 이유가 있을까요...?

2024-01-11 02:17 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
> +        message.setText(code + "\n해윙 ㅋㅋㅋㅋㅋㅋ 인증 문자 보내기 성공 ㅋㅅㅋ");
???????????????

2024-01-11 02:17 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/RedisService.java
> +    }
UserService에서만 사용하면 `protected` 어떨까요?

2024-01-11 02:17 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
> +        String title = "smRt store 인증 번호";
private static 선언 or .yml 주입으로 사용하는건 어떨까요?

2024-01-11 02:17 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
> +        }
Exception 발생 조건이 어떻게 되나요?

2024-01-11 08:11 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
> +@Transactional
필요없을 것 같습니다!

2024-01-11 08:13 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
> +        message.setText(code + "\n해윙 ㅋㅋㅋㅋㅋㅋ 인증 문자 보내기 성공 ㅋㅅㅋ");
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-01-11 08:24 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
> +        }
랜덤 숫자로 인증번호를 만들 때 사용하는 알고리즘이 없으면 발생합니다!

2024-01-11 08:33 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
> +        }
알고리즘이 없는 경우가 가능한가요?

2024-01-11 08:44 UTC, voidmelody approved these changes

2024-01-11 08:48 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
> +        }
SecureRandom의 getInstanceStrong 함수가 저 예외를 throw합니다!

2024-01-11 08:55 UTC, suzzingv commented
> test/resources/application.yml 생성대신 main/resources/application.yml 에 profile 분기 방식을 선택한 것 같은데 이유가 있을까요? 추가적으로 테스트에서 redis 활용이 필요할때 `@Testcontainers` 선언으로 자동 생성이 가능한 것으로 알고있는데 따로 test용 config을 작성해주신 이유도 궁금해요!

- test에서는 testcontainer을 이용해 redis container를 띄웁니다. 경민 님이 말씀해주신 대로 @Testcontainers로 레디스를 test container로 띄워서 사용해봤는데 redistemplate를 빈으로 등록할 때 문제가 되더라구요. config에서 redistemplate를 구성하는데, 이 과정에서 redis의 host와 port를 가져와야 합니다. 그런데 테스트 컨테이너를 @Testcontainers로 코드 안에서 구성해버리면 이 db의 host와 port를 config로 가져와 redistemplate를 구성할 때 쓸 수가 없었습니다. 만약 코드 안에서 테스트 컨테이너를 만드려면 redistemplate도 코드 안에서 만들면 되는데 저는 그냥 다 config로 묶는 게 더 낫다는 생각을 했습니다.
여기서 main에서는 test container를 사용하지 않고, test에서는 test container를 사용해야 하므로 config를 다르게 구성해줘야 했습니다. test 시에는 testconfig가, main에서는 config로 빈을 등록하기 위해 profile을 사용하게 되었습니다. 더 좋은 방법이 있으시다면 공유 부탁드립니다!

2024-01-11 08:57 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
> +        }
그럼 일반적인 상황에서는 exception이 발생 안한다고 보고 ignore 처리해도 될 거같아요! 주석으로 Exception 발생 경우 알려주면 좋을 것 같아요 :D

2024-01-11 08:59 UTC, tidavid1 commented
> > test/resources/application.yml 생성대신 main/resources/application.yml 에 profile 분기 방식을 선택한 것 같은데 이유가 있을까요? 추가적으로 테스트에서 redis 활용이 필요할때 `@Testcontainers` 선언으로 자동 생성이 가능한 것으로 알고있는데 따로 test용 config을 작성해주신 이유도 궁금해요!
> 
> * test에서는 testcontainer을 이용해 redis container를 띄웁니다. 경민 님이 말씀해주신 대로 @testcontainers로 레디스를 test container로 띄워서 사용해봤는데 redistemplate를 빈으로 등록할 때 문제가 되더라구요. config에서 redistemplate를 구성하는데, 이 과정에서 redis의 host와 port를 가져와야 합니다. 그런데 테스트 컨테이너를 @testcontainers로 코드 안에서 구성해버리면 이 db의 host와 port를 config로 가져와 redistemplate를 구성할 때 쓸 수가 없었습니다. 만약 코드 안에서 테스트 컨테이너를 만드려면 redistemplate도 코드 안에서 만들면 되는데 저는 그냥 다 config로 묶는 게 더 낫다는 생각을 했습니다.
>   여기서 main에서는 test container를 사용하지 않고, test에서는 test container를 사용해야 하므로 config를 다르게 구성해줘야 했습니다. test 시에는 testconfig가, main에서는 config로 빈을 등록하기 위해 profile을 사용하게 되었습니다. 더 좋은 방법이 있으시다면 공유 부탁드립니다!

`@TestConfiguration` 에 대해서 확인해보면 좋을 것 같습니다!

2024-01-11 09:12 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
> +    private final static String MESSAGE_BODY = "\n인증번호를 입력해주세요.";
private static final!

2024-01-11 09:12 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
> +    private final JavaMailSender javaMailSender;
혹시 이 부분 오토와이어링 잘 작동 하나요?

2024-01-11 09:21 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
> +    private final JavaMailSender javaMailSender;
넵 잘 작동합니다 ㅎㅎ

2024-01-11 09:25 UTC, suzzingv commented
> > > test/resources/application.yml 생성대신 main/resources/application.yml 에 profile 분기 방식을 선택한 것 같은데 이유가 있을까요? 추가적으로 테스트에서 redis 활용이 필요할때 `@Testcontainers` 선언으로 자동 생성이 가능한 것으로 알고있는데 따로 test용 config을 작성해주신 이유도 궁금해요!
> > 
> > 
> > 
> > * test에서는 testcontainer을 이용해 redis container를 띄웁니다. 경민 님이 말씀해주신 대로 @testcontainers로 레디스를 test container로 띄워서 사용해봤는데 redistemplate를 빈으로 등록할 때 문제가 되더라구요. config에서 redistemplate를 구성하는데, 이 과정에서 redis의 host와 port를 가져와야 합니다. 그런데 테스트 컨테이너를 @testcontainers로 코드 안에서 구성해버리면 이 db의 host와 port를 config로 가져와 redistemplate를 구성할 때 쓸 수가 없었습니다. 만약 코드 안에서 테스트 컨테이너를 만드려면 redistemplate도 코드 안에서 만들면 되는데 저는 그냥 다 config로 묶는 게 더 낫다는 생각을 했습니다.
> >   여기서 main에서는 test container를 사용하지 않고, test에서는 test container를 사용해야 하므로 config를 다르게 구성해줘야 했습니다. test 시에는 testconfig가, main에서는 config로 빈을 등록하기 위해 profile을 사용하게 되었습니다. 더 좋은 방법이 있으시다면 공유 부탁드립니다!
> 
> `@TestConfiguration` 에 대해서 확인해보면 좋을 것 같습니다!

- 줄 수랑 동작에는 제가 한 방식이랑 차이강 없는데 왜 이 방식을 추천하시는지 궁금합니다! 실행환경을 분리한다는 의미보다는 테스트할 때의 config를 설정해준다는 의미가 더 적절해서일까요?

2024-01-11 09:52 UTC, tidavid1 commented
> > > > test/resources/application.yml 생성대신 main/resources/application.yml 에 profile 분기 방식을 선택한 것 같은데 이유가 있을까요? 추가적으로 테스트에서 redis 활용이 필요할때 `@Testcontainers` 선언으로 자동 생성이 가능한 것으로 알고있는데 따로 test용 config을 작성해주신 이유도 궁금해요!
> 
> > > 
> 
> > > 
> 
> > > 
> 
> > > * test에서는 testcontainer을 이용해 redis container를 띄웁니다. 경민 님이 말씀해주신 대로 @testcontainers로 레디스를 test container로 띄워서 사용해봤는데 redistemplate를 빈으로 등록할 때 문제가 되더라구요. config에서 redistemplate를 구성하는데, 이 과정에서 redis의 host와 port를 가져와야 합니다. 그런데 테스트 컨테이너를 @testcontainers로 코드 안에서 구성해버리면 이 db의 host와 port를 config로 가져와 redistemplate를 구성할 때 쓸 수가 없었습니다. 만약 코드 안에서 테스트 컨테이너를 만드려면 redistemplate도 코드 안에서 만들면 되는데 저는 그냥 다 config로 묶는 게 더 낫다는 생각을 했습니다.
> 
> > >   여기서 main에서는 test container를 사용하지 않고, test에서는 test container를 사용해야 하므로 config를 다르게 구성해줘야 했습니다. test 시에는 testconfig가, main에서는 config로 빈을 등록하기 위해 profile을 사용하게 되었습니다. 더 좋은 방법이 있으시다면 공유 부탁드립니다!
> 
> > 
> 
> > `@TestConfiguration` 에 대해서 확인해보면 좋을 것 같습니다!
> 
> 
> 
> - 줄 수랑 동작에는 제가 한 방식이랑 차이강 없는데 왜 이 방식을 추천하시는지 궁금합니다! 실행환경을 분리한다는 의미보다는 테스트할 때의 config를 설정해준다는 의미가 더 적절해서일까요?

프로파일로 나누는 방식보다 테스트용 설정을 사용함이 더 적절해보여서였습니다! 다른 의견 있다면 말해주세요 :D

2024-01-11 13:18 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/core/config/RedisConfig.java
사용 안하는 파일이면 삭제하면 될 듯 합니다! :D

2024-01-11 13:18 UTC, tidavid1 commented on src/test/java/com/programmers/smrtstore/core/config/RedisTestConfig.java
테스트 빌드 과정에서 Redis 서버가 존재하지 않아 테스트 빌드에 실패하는 상황을 해결하기위해서 TestContainer를 활용해서 가상의 Redis 서버를 생성 -> 이로 연결하는 방식으로 이해되는데 맞나요?

2024-01-11 18:49 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/core/config/RedisConfig.java
테스트가 아닌 환경에서 필요한 파일입니다!

2024-01-11 18:50 UTC, suzzingv commented on src/test/java/com/programmers/smrtstore/core/config/RedisTestConfig.java
맞습니다!

2024-01-12 02:01 UTC, tidavid1 approved these changes

2024-01-12 03:03 UTC, merged