Feat/#25 keep service
smRt-Egg/BE-05-smRt-store pull request #41
Opened 2023-12-22 08:21 UTC by voidmelody

## Keep 도메인 구현
### Entity
Keep
* id(Auto Increment)
* user_id (USER 테이블 fk)
* product_id (PRODUCT 테이블 fk)
* created_at

### Service
* 찜하기 기능
* 유저가 찜한 항목 조회
* 찜 삭제
* 유저가 찜한 항목 카테고리별 조회(미구현, 이는 추후 product 테이블과 협의)
* 상품에 대한 찜 랭킹 조회 기능

### Service TestCode

2023-12-22 09:22 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    KEEP_NOT_FOUND_ERROR(NOT_FOUND, "해당 요청에 존재하는 찜이 존재하지 않습니다.");
존재하는 찜이 존재하지 않는다는 말이 좀 어색한 것 같아요!

2023-12-22 17:37 UTC, happyjamy requested changes
수고하셨습니다~ 리뷰 읽고 반영해서 카테고리랑 같이 올려주세용👍

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    KEEP_NOT_FOUND_ERROR(NOT_FOUND, "해당 요청에 존재하는 찜이 존재하지 않습니다.");
맨 뒤 ERROR 는 빼도 의미 전달이 충분히 될 것 같습니다!
메세지는 "찜이 존재하지 않습니다" 정도로도 충분 할 것 같습니다!

또 //500 처럼 //404 를 달고 밑에 적어주세요!

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/application/KeepServiceImpl.java
> +        Keep saveKeepEntity = keepRepository.save(keep);
save() 내부 구현이 인자로 받은 entity 를 그대로 return 해주기 때문에 굳이 한번 더 할당 안해도 될 것 같아요.

```
    @Transactional
    public <S extends T> S save(S entity) {
        Assert.notNull(entity, "Entity must not be null.");
        if (this.entityInformation.isNew(entity)) {
            this.em.persist(entity);
            return entity;
        } else {
            return this.em.merge(entity);
        }
    }
```

save 내부 구현입니다. `SimpleJpaRepository.class` 내부에 존재합니다!

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/DeleteKeepResponse.java
>      Boolean isDelete;
id 만 주지 않고 isDelete 가 필요한 이유가 뭘까요?
id 가 오면 잘 지워진것, 아니면 실패한 것 -> 이걸로는 부족한가요?

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/application/KeepServiceImpl.java
> +        if (!keepRepository.existsById(deleteId)) {
existsById 는 내부적으로 findById 를 사용합니다.
그러므로 Optional 를 반환하는 findById 를 사용해서 예외처리까지 체이닝으로 처리하는것이 좋을것 같습니다!
```
    public boolean existsById(ID id) {
        Assert.notNull(id, "The given id must not be null!");
        if (this.entityInformation.getIdAttribute() == null) {
            return this.findById(id).isPresent();
        } else {
        ...
        }
    }
```

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/application/KeepServiceImpl.java
> +        }
```suggestion
keepRepository.findById(deleteId).orElseThrow(() -> new KeepNotFoundException());
```

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/domain/entity/Keep.java
테이블 명 _TB 로 접미사 붙이는거 반영해주세요!

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/domain/entity/Keep.java
>      private LocalDateTime createdAt;
DB 자동 insert 되게 바꿔주세요!

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/exception/KeepNotFoundException.java
> +public class KeepNotFoundException extends CustomException {
저는 굳이 Exception 을 상황마다 안만들고
KeepException 하나 만들어서 ErrorCode 로 구분하는데 어떻게 생각하시나요?

2023-12-22 17:37 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/infrastructure/KeepJpaRepository.java
> +    @Query("SELECT new com.programmers.smrtstore.domain.keep.presentation.dto.res.KeepRankingResponse(k.productId, COUNT(k.productId)) " +
dto 로 가져올꺼면 쿼리dsl 로 변경해주세요!

2023-12-23 03:06 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    KEEP_NOT_FOUND_ERROR(NOT_FOUND, "해당 요청에 존재하는 찜이 존재하지 않습니다.");
[200 vs 404](https://techblog.yogiyo.co.kr/%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B0%80-%EC%97%86%EC%9D%84-%EB%95%8C-200%EC%9D%B8%EA%B0%80-404%EC%9D%B8%EA%B0%80-f1c8c39ca9df) 한번 고려해보면 좋을 것 같습니다 :D

2023-12-23 03:10 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/keep/application/KeepService.java
Service에 대해서 인터페이스를 작성한 이유는 다른 기능 개발 과정에서 필요한 메서드나 요소를 미리 작성해두어 혼선을 방지하고자 구현을 진행했던 부분입니다. 구현 과정에서 인터페이스를 클래스로 전환해서 사용하는 것이 더 좋지 않았을까? 라는 생각이 있는데 의견이 궁금합니다 :D

2023-12-23 03:11 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/keep/application/KeepServiceImpl.java
> +        if (!keepRepository.existsById(deleteId)) {
findById 사용 이후 Optional 의 ifPresent나 ifPresentOrElse 활용도 좋아보입니다

2023-12-23 03:24 UTC, tidavid1 requested changes

2023-12-23 03:24 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/KeepResponse.java
> +    }
정적 스태틱 메서드를 활용하는 방식은 좋은것 같습니다 👍🏻
스태틱 메서드에서 사용하는 KeepResponse 생성자가 메서드에서  받는 파라미터 그대로를 적용하는 것이 타당할까? 생각해보면 좋을 것 같습니다.

```suggestion
    private KeepResponse(Long id, Long userId, Long productId) {
        this.id = id;
        this.userId = userId;
        this.productId = productId;
    }

    public static KeepResponse of(Keep keep) {
        return new KeepResponse(
            keep.getId(),
            keep.getUserId(),
            keep.getProductId()
        );
    }
```

2023-12-23 03:24 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/DeleteKeepResponse.java
> +    }
한 개의 파라미터를 받는 정적 스태틱 메서드는 `from` 네이밍이 좋지 않을까요?

[Static Factory Method](https://exponential-e.tistory.com/74)

2023-12-23 07:40 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/application/KeepService.java
어짜피 상속받는 class 가 하나라 상관 없지 않을까요?

2023-12-23 13:29 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/keep/application/KeepService.java
상속받는 클래스가 하나니까 상속이 필요 없을 것 같다는 의견이었습니다 :D

2023-12-24 05:48 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/DeleteKeepResponse.java
> +    }
네 From으로 변경하겠습니다.

2023-12-24 06:01 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/keep/domain/entity/Keep.java
>      private LocalDateTime createdAt;
생성자에서 createdAt을 초기화해서, 문제가 없지 않을까요?

2023-12-24 06:13 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/DeleteKeepResponse.java
>      Boolean isDelete;
그렇게 하겠습니다

2023-12-24 06:35 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    KEEP_NOT_FOUND_ERROR(NOT_FOUND, "해당 요청에 존재하는 찜이 존재하지 않습니다.");
에러를 반환하기 보다는, 200으로 반환하는 대신에 빈 데이터를 보내는 식으로 수정하겠습니다

2023-12-24 06:38 UTC, voidmelody commented on src/main/java/com/programmers/smrtstore/domain/keep/exception/KeepNotFoundException.java
> +public class KeepNotFoundException extends CustomException {
해당 방식으로 구현할게요!

2023-12-25 16:03 UTC, YongNyeo approved these changes

2023-12-25 16:31 UTC, happyjamy requested changes

2023-12-25 16:31 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/keep/domain/entity/Keep.java
> +@Table(name = "keeps_TB")
keep_TB 아닌가요

2023-12-26 00:06 UTC, happyjamy approved these changes

2023-12-26 00:08 UTC, tidavid1 approved these changes

2023-12-26 00:13 UTC, suzzingv approved these changes

2023-12-26 00:16 UTC, merged