Feat/#31 user service
smRt-Egg/BE-05-smRt-store pull request #46
Opened 2023-12-22 14:27 UTC by suzzingv

signUp 기능구현
시큐리티 오류 수정

- gradle Guava 삭제 필요

2023-12-22 17:38 UTC, happyjamy commented
메인에 올렸어요 develop 로 브렌치 변경해주세요~

2023-12-23 13:31 UTC, tidavid1 commented on .gitignore
> +docker-compose.yaml
docker-compse.yaml 파일이 필요한 이유가 있을까요?

2023-12-23 13:44 UTC, tidavid1 requested changes
테스트 코드 작성해주시면 감사하겠슴다! 리뷰 적어놓은거 확인해주세요 :D

2023-12-23 13:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/SmRtStoreApplication.java
> +@EnableJpaAuditing
`@LastModifiedDate`, `@CreatedDate` 대신 `@CreationTimestamp`, `@UpdateTimestamp` 을 활용하는 방향으로 수정하면 좋을 것 같습니다 :D

2023-12-23 13:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    NOT_FOUND_USER(NOT_FOUND, "user을 찾을 수 없습니다.");
NOT_FOUND_USER 보다 USER_NOT_FOUND 네이밍이 더 어울릴 수도 있을거 같아요! 의견이 궁금합니다

2023-12-23 13:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
> +@Slf4j
로깅이 보이지 않는데 어노테이션을 추가한 이유가 있을까요?

2023-12-23 13:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
> +        return userRepository.findByAuth_LoginId(loginId).isPresent();
메소드를 일부러 분리한 이유가 있을까요?

2023-12-23 13:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
몇개 필드에 대해서는 `@Column` 어노테이션이 누락된 것 같슴다. 확인해주세요 :D

2023-12-23 14:12 UTC, happyjamy requested changes
수정 사항 반영해주세요~

2023-12-23 14:12 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/exception/GlobalExceptionHandler.java
> +            .body(e.getMessage());
BindingResult 를 따로 빼서 처리하는게 좋아보여요!

```suggestion
public class ValidationErrorResponse {
    private String field;
    private String message;
    private Object rejectedValue;

    // 생성자, getter, setter 등
    public ValidationErrorResponse(String field, String message, Object rejectedValue) {
        this.field = field;
        this.message = message;
        this.rejectedValue = rejectedValue;
    }

    // getter와 setter 메소드...
}

@ExceptionHandler(value = {
        BindException.class,
        MethodArgumentNotValidException.class
})
public ResponseEntity<List<ValidationErrorResponse>> validationError(BindException e) {
    BindingResult bindingResult = e.getBindingResult();

    List<ValidationErrorResponse> errors = new ArrayList<>();
    for (FieldError fieldError : bindingResult.getFieldErrors()) {
        ValidationErrorResponse error = new ValidationErrorResponse(
                fieldError.getField(),
                fieldError.getDefaultMessage(),
                fieldError.getRejectedValue()
        );
        errors.add(error);
    }
    return ResponseEntity.badRequest().body(errors);
}

```

2023-12-23 14:22 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
>  public class UserService {
클래스 단위로 붙이는 방식 관련해서 간단하게 읽어보면 좋을 것 같아 내용 첨부합니다!
[@Transactional의 대체 정책(Fallback Policy)](https://mangkyu.tistory.com/170)

2023-12-23 14:23 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
>  public class UserService {
클래스 단위로 붙이는 방식 관련해서 간단하게 읽어보면 좋을 것 같아 내용 첨부합니다!
[@Transactional의 대체 정책(Fallback Policy)](https://mangkyu.tistory.com/170)

2023-12-23 19:49 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
딱히 조건을 설정해주지 않아도 되는 필드에는 @column을 붙여주지 않았습니다!

2023-12-23 19:54 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    NOT_FOUND_USER(NOT_FOUND, "user을 찾을 수 없습니다.");
400대 500대 이렇게 나눠 적는 건 줄 알았습니다 ㅎㅅㅎ

2023-12-23 19:56 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/exception/UserException.java
> +        String runtimeValue) {
데둉함니다...

2023-12-25 15:48 UTC, tidavid1 requested changes

2023-12-25 16:12 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
>  public class User {
저번에 말씀드린 User에 신규고객(NEW),재구매고객(RE) enum으로 필드 생성해주세요!

2023-12-25 16:47 UTC, voidmelody approved these changes

2023-12-26 00:05 UTC, happyjamy approved these changes

2023-12-26 00:05 UTC, tidavid1 approved these changes

2023-12-26 00:06 UTC, YongNyeo approved these changes

2023-12-26 02:01 UTC, merged