Feat/#34 coupon domain
smRt-Egg/BE-05-smRt-store pull request #47
Opened 2023-12-23 06:48 UTC by YongNyeo

### Entity 

UserCoupon 구현
- User에게 어떤 Coupon이 있는지 연결 테이블로서 역할
- User가 갖고있는 Coupon에 대해 소유 여부와, 발급 횟수를 저장

ProductCoupon 구현
- Product에 적용되는 Coupon을 알수 있는 연결 테이블로서 역할

2023-12-23 07:58 UTC, happyjamy reviewed
확인 완료!

2023-12-23 07:58 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/ProductCoupon.java
> +        uniqueConstraints = {
ddl 옵션을 사용 안한다면 이걸 명시한 이유가 있나요?

2023-12-23 07:58 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/UserCoupon.java
> +    public void increaseIssueCount() {
외부에서 따로 호출 안하면 private 해주세요~

2023-12-23 07:58 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/UserCoupon.java
> +    public void downloadCoupon() {
쿠폰 다운이라는 행위는 
1. 이미 다운 된 쿠폰인지 확인한다.
2-1. 다운 된 쿠폰이라면 해당 쿠폰이 몇번까지 다운 가능한지 확인한다.
2-1-1. 다운 가능하다면 issueCount 증가
2-2. 다운 되지 않은 쿠폰이라면 entity 만들기

해당 로직들이 모두 포함되어야 하지 않나 라는 생각이 듭니다!

2023-12-23 10:43 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/UserCoupon.java
> +    public void downloadCoupon() {
쿠폰을 실제 다운하는 로직은
Coupon객체와 UserCoupon 객체가모두 필요해서 서비스에서 진행될 예정이었습니다!
이 메서드는 서비스에서 로직 통과하고나서 나중에 UserCoupon의 상태 변경 메서드였습니다
메서드명을 변경해야할까요?..

2023-12-23 11:14 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/UserCoupon.java
> +    public void downloadCoupon() {
네 이름변경이 필요할 듯 보이네요!

외부 객체 조회는 서비스에서 하지만 validate 는 도메인 안에서 하시는걸 추천 드립니다.

2023-12-25 04:18 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/ProductCoupon.java
> +        uniqueConstraints = {
ddl 옵션이 혹시 jpa매핑시 사용하는 cascade  말씀하시는걸까요??
제가 질문을 이해를 잘 못했습니다 ㅠ

2023-12-26 00:14 UTC, suzzingv approved these changes

2023-12-26 14:50 UTC, suzzingv approved these changes

2023-12-26 15:17 UTC, voidmelody approved these changes

2023-12-26 15:39 UTC, happyjamy requested changes

2023-12-26 15:39 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    NOT_MEMBERSHIP(OK, "멤버쉽 유저 전용 쿠폰입니다"),
다 200으로 처리한 이유가 있을까요?

2023-12-26 15:39 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    private Coupon(CouponValue couponValue, boolean membershipCouponYn, boolean duplicationYn, boolean availableYn, CouponType couponType, BenefitUnitType benefitUnitType, CustomerManageBenefitType c
빌더로 쓰면 가독성 더 좋을것 같아요!

2023-12-26 15:39 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    public static Coupon of(CreateCouponRequest request) {
파라미터가 1개면 from 이 더 어울리는것 같아요!

2023-12-26 15:39 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    public void validCoupon() {
validateCoupon() 아니고 validCoupon() 인 이유가 뭘까요?

2023-12-26 15:39 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponQuantity.java
> +    public void increase(int num) {
동시성 문제 생각해서 sql 로 insert 하게 짜주세요~

2023-12-26 15:39 UTC, happyjamy commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/ProductCoupon.java
이름 좀 더 쿠폰을 사용할 수 있는 product 이런느낌으로 바꾸는게 어떤가요

2023-12-26 17:53 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
> +    NOT_MEMBERSHIP(OK, "멤버쉽 유저 전용 쿠폰입니다"),
모두 리소스의 상태에 대한 예외처리라고 생각해서 정상흐름(OK)으로 처리해도 될 것이라고 생각했습니다
다만  마지막 COUPON_NOT_FOUND의 경우 리소스를 찾을수 없는 것이라 NOT FOUND로 처리해도 될 것 같다는 생각입니다!

2023-12-26 17:54 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    public void validCoupon() {
그동안 잘못 써온 관습 같습니다!

2023-12-27 00:24 UTC, tidavid1 reviewed
가능하다면 테스트코드도 작성해주세요 :D

2023-12-27 00:24 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponValue.java
> +    }
빌더와 동일한 파라미터를 받는 정적 스태틱 메서드를 작성한 이유가 있을까요??

2023-12-27 00:49 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponValue.java
> +    }
빌더를 써야하나 정적 메서드를 써야하나 고민하다가 둘다 남겨진 것 같습니다
빌더를 삭제해야하나 싶지 않을까 싶습니다!!

2023-12-27 00:52 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/ProductCoupon.java
이걸 DB에는 적용하긴했는데
딱히 괜찮은 네이밍이 생각이 안나서...
CouponAppliedProduct  또는 CouponAvailableProduct 또는 CouponUsuableProduct 정도인데 
추천도 받습니다!!!

2023-12-27 01:49 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
> +    private Coupon(CouponValue couponValue, boolean membershipCouponYn, boolean duplicationYn, boolean availableYn, CouponType couponType, BenefitUnitType benefitUnitType, CustomerManageBenefitType c
저도 Coupon에 한해서는 정적 팩토리 메서드 대신 빌더를 적용하는게 좋다고 생각되네용!!

2023-12-27 02:06 UTC, tidavid1 approved these changes

2023-12-27 02:15 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/ProductCoupon.java
Available을 사용하는게 좋아보입니다~

2023-12-27 02:20 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/UserCoupon.java
> +            throw new CouponException(ErrorCode.COUPON_ALREADY_USE, String.valueOf(useYn));
ErrorCode.COUPON_ALREADY_USED가 좀 더 깔끔해보이는데 어떻게 생각하세요~?

2023-12-27 02:21 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/UserCoupon.java
> +            throw new CouponException(ErrorCode.NOT_MEMBERSHIP, String.valueOf(userMembership));
찾아보니 NOT_MEMBERSHIP보다 NON_MEMBERSHIP이 좀 더 자주 사용되는 것 같아요!

2023-12-27 03:32 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/UserCoupon.java
> +            throw new CouponException(ErrorCode.COUPON_ALREADY_USE, String.valueOf(useYn));
사용된이라는 의미는 USED가 더 적합하겠네요! 👍

2023-12-27 06:58 UTC, JIN-076 approved these changes

2023-12-28 03:58 UTC, closed without merging