Feat/#53 user service
smRt-Egg/BE-05-smRt-store pull request #55
Opened 2023-12-26 14:38 UTC by suzzingv

## Service, Controller
- me : 토큰으로 회원 정보 조회
- findByUserId : user id로 회원 정보 조회
- update : 회원 정보 수정
- withdraw : 회원 탈퇴

## 얘기해보고 싶은 사항
- builder을 사용하지 않고 정적팩토리 메서드로 생성자로 객체를 생성했습니다. 그런데 이러면 만약 고객이 상품을 재구매할 때repuchaseYN의 상태를 true로 바꿀 경우, user의 다른 모든 정보도 모두 다시 넣어주거나, 다른 정보들은 null로 보내고 객체를 변경할 경우 null 체크를 해줘야 합니다. 필드가 너무 많아 코드가 다소 복잡해질 것 같은데, 어떻게 생각하는지 궁금합니다.

- 조회, 수정, 탈퇴 시 인증이 필요하다고 생각해 토큰을 이용해 사용자 정보를 등록하고 가져오도록 구현했습니다. 이때 인증을 위한 객체들 생성을 수정, 삭제 시마다 해줘야할지 service에 생성해놓고 사용해야할지에 대한 의견이 궁금합니다.

- findByUserId가 필요한지에 대한 생각이 궁금합니다.

## 요청사항
- gradle guava 삭제..!

2023-12-27 00:44 UTC, tidavid1 requested changes
User에서 Builder 패턴을 사용하는데 내부에 생성자를 따로 만들어서 활용하는 이유가 궁금해요!

가능하다면 테스트 작성해주시면 감사하겠습니다 :D

2023-12-27 00:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthentication.java
> +import org.springframework.stereotype.Component;
안쓰는 import 지워주세요!

2023-12-27 00:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
> +@Slf4j
불필요한 어노테이션은 지워주세요 :D

2023-12-27 00:44 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Auth.java
> +    }
로그인 하는 ID를 업데이트하는 경우가 있을까요?? + ID는 유니크한 값이라고 생각하는데 의견이 궁금해요

2023-12-27 00:54 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthentication.java
> +import org.springframework.stereotype.Component;
아니 이게 왜 또..

2023-12-27 00:55 UTC, suzzingv commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Auth.java
> +    }
로그인 아이디는 수정할 수 있다고 생각합니다! 수정할 때 중복검사를 거쳐 유니크하도록 만들 수 있다고 생각합니다!

2023-12-27 01:00 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Auth.java
> +    }
DB Column에서도 Unique를 활용하면 좋을 것 같슴다 👍🏻

2023-12-27 01:51 UTC, YongNyeo commented
저도 빌더랑 정적 팩토리 메서드 고민을 계속 해왔는데...
필드가 많아지면 많아질수록 가독성때문이라도 빌더 쓰는게 맞는 것 같습니다.
개인적으로는 정적 팩토리메서드는 객체 생성시 값 검증같은 로직이 들어가는 경우에 사용하면 더 좋다고 생각됩니다!!

2023-12-27 02:03 UTC, tidavid1 approved these changes

2023-12-27 02:12 UTC, YongNyeo approved these changes

2023-12-27 14:24 UTC, tidavid1 approved these changes

2023-12-28 03:18 UTC, voidmelody approved these changes

2023-12-28 03:27 UTC, JIN-076 approved these changes

2023-12-28 04:41 UTC, merged