Feat/#59 coupon download
smRt-Egg/BE-05-smRt-store pull request #73
Opened 2023-12-29 08:00 UTC by YongNyeo

- [ ] CouponApiController의 save() 구현

- [ ] UserCouponService 의 save() 구현

- [ ] CouponAvailableUserJpaRepository 구현

- [ ] CouponQueryRepository 의 findCounponById() 구현

2023-12-29 11:52 UTC, tidavid1 requested changes
Request, Response DTO에 전달하는 객체가 id값 하나인 경우들인데 값 직접 전달 방식 외에 DTO를 활용한 이유가 궁금합니다! 어떤 이점이 있을까요??

2023-12-29 11:52 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +    public SaveCouponResponse save(SaveCouponRequest request, Long userId) {
코드 컨벤션 지켜주세요! :D 👍🏻

2023-12-29 11:52 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/presentation/CouponApiController.java
> +    public void save(@RequestAttribute(value = "userId") Long userId, @PathVariable Long id,
추후 AOP 방식으로 변경되면 변경 부탁드립니다 :D 👍🏻

2023-12-29 11:52 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/presentation/CouponApiController.java
> +                     @RequestBody SaveCouponRequest request) {
DTO 검증 추가해야 할 것 같아요!

2023-12-29 11:52 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/SaveCouponRequest.java
>  }
Validation 추가해주세요!

2023-12-29 11:52 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +    }
Optional 객체에 대해서 ifPresentOrElse 등 으로 한번에 처리하는 것은 어떨까요?

2023-12-30 05:52 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +    public SaveCouponResponse save(SaveCouponRequest request, Long userId) {
혹시 줄바꿈 말씀하시는게 맞을까요??

2023-12-30 07:56 UTC, YongNyeo commented
> Request, Response DTO에 전달하는 객체가 id값 하나인 경우들인데 값 직접 전달 방식 외에 DTO를 활용한 이유가 궁금합니다! 어떤 이점이 있을까요??

값이 한개임에도 dto를 쓴 이유는 그냥 CouponId를 넘겨주면 제가 아닌 다른분들이 코드를 볼 때 혼동이 오기 더 쉽다고  생각해서 
웬만하면 dto를 사용하자고했습니다.

2023-12-30 08:10 UTC, suzzingv approved these changes

2023-12-30 08:11 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponQueryRepository.java
QueryDSL을 사용하는 Repository를 CouponJPARepository에 통합시켜 사용하지 않고 분리해서 사용하는 이유가 궁금합니다!

2023-12-30 08:11 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
어떤 역할을 하는 코드인지 설명해주실수 있을까요?

2023-12-30 08:20 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponQueryRepository.java
querydsl 은 queryFactory 의존성도 받아야하고 
spring data jpa 의 룰에 따라 메서드 네이밍으로 작동하는 레포지토리랑
직접 쿼리를 만들어야하는 레포지토리랑은 구분해서 사용하는게 가독성에 훨씬 좋다고 생각합니다!

2023-12-30 08:29 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
이전에 Coupon자체에 락을 걸었는데, 수정하면서 CouponQuantity에만 락을 걸고자했습니다.
Pessimistic 대신 Optimistic을 사용했는데,
Optimistic은 락을 한번에 얻지 못하면 OptimisticLockException이 발생합니다.
따라서 락을 계속 얻으려면 예외처리를 항상해줘야하는데 
서비스에서 진행하는 방법도 있지만 layer들 사이에서  facade 패턴을 이용한다고 합니다!

2023-12-30 16:34 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +                .orElseThrow(() -> new UserException(ErrorCode.USER_NOT_FOUND, "false"));
UserException에 ErrorCode 넘겨줄 때 runtimeValue로 false를 넣는 이유?가 궁금합니당!

2023-12-30 16:42 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +                .orElseThrow(() -> new UserException(ErrorCode.USER_NOT_FOUND, "false"));
userId 나 couponId를 뭔가 직접적으로 반환해도 될까? 라는 생각에 대신 false를 넣자 라는 의도였습니다
다시 생각해보니 couponId나 userId정도는 그냥 반환해도 괜찮을 것 같은데 , 지인님은 어떻게 구현하셨나요?!

2023-12-31 04:21 UTC, tidavid1 approved these changes

2023-12-31 04:21 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +                .orElseThrow(() -> new UserException(ErrorCode.USER_NOT_FOUND, "false"));
저는 UserException으로 에러가 발생했을 때 userId가 사용자가 알 필요가 없는 값이라고 생각해서 ErrorCode만 반환하는 생성자를 별도로 두어서 따로 값을 반환하지 않았습니다!

2023-12-31 04:30 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +                .orElseThrow(() -> new UserException(ErrorCode.USER_NOT_FOUND, "false"));
그리고 해당 로직은 해당 사용자가 유효한 사용자인지 검증하는 것이라고 생각이 되어서 '사용자를 찾을 수 없습니다'라는 404 오류를 반환하는 것보다 '유효하지 않은 사용자입니다'같은 메시지와 함께 Unauthorized 코드를 반환하는게 좀 더 명확할 것 같은데 어떻게 생각하시나용?

2023-12-31 04:41 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
> +public class CouponQuantityFacade {
이 클래스는 쿠폰 수량? 재고? 관련된 로직을 통합해서 다루는 클래스라는 의미로 Facade를 넣은게 맞을까요? facade 패키지를 따로 별도로 두고 Facade 클래스로 분리해서 구현한 이유가 궁금합니당!

2023-12-31 04:47 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponQueryRepository.java
> +
WTF?!

2023-12-31 04:56 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +        Optional<CouponAvailableUser> couponAvailableUser = couponAvailableUserJpaRepository.findByCouponIdAndUserId(couponId, userId);
CouponAvailableUser 클래스는 어디에서 볼 수 있나용?

2023-12-31 06:27 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +        Optional<CouponAvailableUser> couponAvailableUser = couponAvailableUserJpaRepository.findByCouponIdAndUserId(couponId, userId);
도메인에 있습니다..

2023-12-31 06:29 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponQueryRepository.java
> +
레포지토리랑 서비스에 미리 작성해둔 부분이 많은데 커밋 쪼개서 진행하느라 import나 줄바꿈부분에 뭐가 좀 많을수있는데
양해부탁드립니다 👍

2023-12-31 06:31 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
> +public class CouponQuantityFacade {
수량의 재고만 담당하는 부분입니다. 
재고도 엄연히 하나의 엔티티(테이블)이기때문에 따로 분리해서 구현하는게 맞다고 생각했고,
facade 패키지는 별도의 레이어로 보기 어렵지만 infrastructure랑 밀접한 관련이 있어서 그 안에 위치하고있습니다.

2023-12-31 06:40 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +                .orElseThrow(() -> new UserException(ErrorCode.USER_NOT_FOUND, "false"));
좋은 아이디어같습니다!
다만 저희 회의때 얘기했던 
회원이 존재하는지에 대한 DB검증이 반드시 있어야한다고해서 넣은 부분이라 모든 메서드에 user찾는 부분은 404로 넣었고...
쿠폰에 유효하지 않은 회원이 접근하는 검증 로직은 CouponAvailableUser 도메인부분에 따로 있습니다. 
그쪽에 있는 Errorcode status는 401로 바꿔도 좋을 것 같습니다 👍

2023-12-31 07:45 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
> +        Optional<CouponAvailableUser> couponAvailableUser = couponAvailableUserJpaRepository.findByCouponIdAndUserId(couponId, userId);
제가 머지를 안해서 안 보이는거였네요👍🏻

2023-12-31 11:00 UTC, merged