Refact/#74 refact user 정보 보여주기
smRt-Egg/BE-05-smRt-store pull request #75
Opened 2023-12-29 10:00 UTC by suzzingv

- dto 수정
- 현재 로그인한 userId 가져오는 방법 수정
- url 수정

2023-12-29 11:57 UTC, tidavid1 requested changes

2023-12-29 11:57 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/ProfileUserResponse.java
>      private boolean marketingAgree;
필요한 정보만 전달하는건 매우 좋은 수정인것 같아요! 👍🏻

2023-12-29 11:57 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/ProfileUserResponse.java
> +    public static ProfileUserResponse toDetailUserResponse(User user) {
정적 팩토리 메서드 네이밍 방식에 대해서 조금 더 살펴보면 좋을 것 같습니다!

[Effective Java: 아이템 1. 생성자 대신 정적 팩토리 메서드를 고려하라](https://sun-22.tistory.com/84)

2023-12-29 11:57 UTC, tidavid1 commented on src/main/java/com/programmers/smrtstore/domain/user/presentation/UserController.java
Controller `@RequestMapping` 에서 엔드포인트 위치를 "/api/v1/auth/user" -> "/api/v1/user" 로 바꿔야 할 것 같습니다! 👍🏻

2023-12-29 11:58 UTC, tidavid1 requested changes
브랜치명에 한글이 포함되면 한글이 안보이는 케이스가 생길수도 있어요!

2023-12-30 02:26 UTC, tidavid1 approved these changes

2023-12-30 13:39 UTC, YongNyeo commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
>          user.updateUser(request.getAge(), request.getNickName(), request.getEmail(),
dto에 대한 파라미터를 일일이 service에서 나열하는것보다 dto static메서드 내에서 처리하는게 더 깔끔할것 같아요 ! 😄

2023-12-30 13:39 UTC, YongNyeo approved these changes

2023-12-31 05:56 UTC, JIN-076 commented on src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
> +        User user = userRepository.findById(userId)
해당 로직이 다른 클래스에서도 중복으로 사용되는 경우가 많은데 따로 메서드로 분리해서 사용하는 것도 좋을 것 같아요!

2023-12-31 06:14 UTC, JIN-076 approved these changes

2023-12-31 06:29 UTC, merged